---
- hosts: all
  vars:
    user: jordan
    srcdir: /home/{{user}}/src/prelude
  tasks:
    - name: Copy source
      synchronize:
        src: ../
        dest: "{{srcdir}}"
        rsync_opts:
          - "--exclude=.git"
    - name: Prepare
      command:
        chdir: "{{srcdir}}"
        cmd: gmake clean
    - name: Compile
      command:
        chdir: "{{srcdir}}"
        cmd: gmake
        #    - name: Execute
