---
- hosts: all
  vars:
    user: jordan
    srcdir: /home/{{user}}/src/prelude
  tasks:
    - name: Copy source
      synchronize:
        # Why do we need to go up 2 directories here? Bug in syncronize module?
        src: ../../
        dest: "{{srcdir}}"
        rsync_opts:
          - "--exclude=.git"
    - name: Prepare
      command:
        chdir: "{{srcdir}}"
        cmd: gmake clean
    - name: Compile
      command:
        chdir: "{{srcdir}}"
        cmd: gmake
    - name: Execute
      command:
        chdir: "{{srcdir}}"
        cmd: ./prelude
